// 用户登录注册相关
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const SET_REGISTER_ERROR_MSG = 'REGISTER_ERROR_MSG';
export const SET_LOGIN_ERROR_MSG = 'LOGIN_ERROR_MSG';
export const CHANGE_USER_LIST = 'CHANGE_USER_LIST';
export const LOGOUT = 'LOGOUT';